type HouseItem = {
    id: number;
    name: string;
    title: Record<Language, string>;
    long_title: Record<Language, string>;
    decor_text: Record<Language, string>;
    description: Record<Language, string>;
    photo: string[];
    cover_photo: string;
    rental_price: number;
    max_adults: number;
    is_available: boolean;
    discount_percent: number;
    extra_adults: number;
    extra_children: number;
    extra_adult_price: number;
    extra_children_price: number;
    rooms: HouseItem[] | [];
    photoDecor: string;
    treesDecor: string;
    coordinates: {
        top: number;
        left: number;
        topSmall: number;
        leftSmall: number;
        topSmallDifference: number;
        leftSmallDifference: number;
        topMedium: number;
        leftMedium: number;
        topMediumDifference: number;
        leftMediumDifference: number;
        topLarge: number;
        leftLarge: number;
    };
};
