import Breadcrumbs from "@/components/Breadcrumbs/Breadcrumbs";
import Footer from "../../../components/Footer/Footer";
import Header from "../../../components/Header/Header";
import AskGrandpa from "@/components/AskGrandpa/AskGrandpa";

// import "../../globals.scss";
import Navigation from "@/components/Header/Navigation";

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <Navigation />
      <Breadcrumbs />
      {children}
      <AskGrandpa />
      <Footer />
    </>
  );
}
