<<<<<<< HEAD
import Footer from "../../../components/Footer/Footer";
import Header from "../../../components/Header/Header";
import "../../globals.scss";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
=======
import Breadcrumbs from "@/components/Breadcrumbs/Breadcrumbs";
import Footer from "../../../components/Footer/Footer";
import Header from "../../../components/Header/Header";

import Navigation from "@/components/Header/Navigation";
>>>>>>> 5a28b413a7eea541795a727d3e7a5a390ead1c01

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
<<<<<<< HEAD
      {children}
=======
      <Navigation />
      <Breadcrumbs />
        {children}
>>>>>>> 5a28b413a7eea541795a727d3e7a5a390ead1c01
      <Footer />
    </>
  );
}
