name: telegram message
on: 
  push:
    branches:
      - develop
      - master
      - admin
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    name: Notify Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message on pull request
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} created a pull request on branch `${{ github.head_ref }}`:
            Pull request: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})

      - name: Send Telegram message on merge to develop
        if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/develop') }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            The branch `${{ github.ref_name }}` was successfully merged by ${{ github.actor }}! 
            See latest commit: ${{ github.event.head_commit.url }}
